// 用于将 ECharts/GeoJSON 英文国家名映射到中英文显示名
const COUNTRY_NAME_FALLBACK: Record<string, { zh: string; en: string }> = {
  // 大中华区
  "Hong Kong": { zh: "香港", en: "Hong Kong" },
  Macao: { zh: "澳门", en: "Macao" },
  Taiwan: { zh: "台湾", en: "Taiwan" },
  China: { zh: "中国大陆", en: "China" },
  // 东亚
  Japan: { zh: "日本", en: "Japan" },
  "South Korea": { zh: "韩国", en: "South Korea" },
  "North Korea": { zh: "朝鲜", en: "North Korea" },
  "Dem. Rep. Korea": { zh: "朝鲜", en: "North Korea" },
  Mongolia: { zh: "蒙古", en: "Mongolia" },
  // 东南亚
  Singapore: { zh: "新加坡", en: "Singapore" },
  Malaysia: { zh: "马来西亚", en: "Malaysia" },
  Thailand: { zh: "泰国", en: "Thailand" },
  Vietnam: { zh: "越南", en: "Vietnam" },
  Philippines: { zh: "菲律宾", en: "Philippines" },
  Indonesia: { zh: "印度尼西亚", en: "Indonesia" },
  Myanmar: { zh: "缅甸", en: "Myanmar" },
  Cambodia: { zh: "柬埔寨", en: "Cambodia" },
  Laos: { zh: "老挝", en: "Laos" },
  "Timor-Leste": { zh: "东帝汶", en: "Timor-Leste" },
  "East Timor": { zh: "东帝汶", en: "Timor-Leste" },
  Brunei: { zh: "文莱", en: "Brunei" },
  "Brunei Darussalam": { zh: "文莱", en: "Brunei" },
  // 南亚
  India: { zh: "印度", en: "India" },
  Pakistan: { zh: "巴基斯坦", en: "Pakistan" },
  Bangladesh: { zh: "孟加拉国", en: "Bangladesh" },
  "Sri Lanka": { zh: "斯里兰卡", en: "Sri Lanka" },
  Nepal: { zh: "尼泊尔", en: "Nepal" },
  Bhutan: { zh: "不丹", en: "Bhutan" },
  Maldives: { zh: "马尔代夫", en: "Maldives" },
  Afghanistan: { zh: "阿富汗", en: "Afghanistan" },
  // 中亚
  Kazakhstan: { zh: "哈萨克斯坦", en: "Kazakhstan" },
  Uzbekistan: { zh: "乌兹别克斯坦", en: "Uzbekistan" },
  Turkmenistan: { zh: "土库曼斯坦", en: "Turkmenistan" },
  Tajikistan: { zh: "塔吉克斯坦", en: "Tajikistan" },
  Kyrgyzstan: { zh: "吉尔吉斯斯坦", en: "Kyrgyzstan" },
  // 高加索
  Azerbaijan: { zh: "阿塞拜疆", en: "Azerbaijan" },
  Armenia: { zh: "亚美尼亚", en: "Armenia" },
  Georgia: { zh: "格鲁吉亚", en: "Georgia" },
  // 中东
  Turkey: { zh: "土耳其", en: "Turkey" },
  "United Arab Emirates": { zh: "阿联酋", en: "United Arab Emirates" },
  "Saudi Arabia": { zh: "沙特阿拉伯", en: "Saudi Arabia" },
  Israel: { zh: "以色列", en: "Israel" },
  Palestine: { zh: "巴勒斯坦", en: "Palestine" },
  "West Bank": { zh: "巴勒斯坦", en: "Palestine" },
  Iraq: { zh: "伊拉克", en: "Iraq" },
  Iran: { zh: "伊朗", en: "Iran" },
  Syria: { zh: "叙利亚", en: "Syria" },
  Jordan: { zh: "约旦", en: "Jordan" },
  Lebanon: { zh: "黎巴嫩", en: "Lebanon" },
  Kuwait: { zh: "科威特", en: "Kuwait" },
  Qatar: { zh: "卡塔尔", en: "Qatar" },
  Bahrain: { zh: "巴林", en: "Bahrain" },
  Oman: { zh: "阿曼", en: "Oman" },
  Yemen: { zh: "也门", en: "Yemen" },
  // 北美
  "United States of America": { zh: "美国", en: "United States of America" },
  Canada: { zh: "加拿大", en: "Canada" },
  Mexico: { zh: "墨西哥", en: "Mexico" },
  Greenland: { zh: "格陵兰", en: "Greenland" },
  "Saint Pierre and Miquelon": {
    zh: "圣皮埃尔和密克隆",
    en: "Saint Pierre and Miquelon",
  },
  // 中美洲
  Guatemala: { zh: "危地马拉", en: "Guatemala" },
  Belize: { zh: "伯利兹", en: "Belize" },
  Honduras: { zh: "洪都拉斯", en: "Honduras" },
  "El Salvador": { zh: "萨尔瓦多", en: "El Salvador" },
  Nicaragua: { zh: "尼加拉瓜", en: "Nicaragua" },
  "Costa Rica": { zh: "哥斯达黎加", en: "Costa Rica" },
  Panama: { zh: "巴拿马", en: "Panama" },
  // 加勒比
  Cuba: { zh: "古巴", en: "Cuba" },
  Jamaica: { zh: "牙买加", en: "Jamaica" },
  Haiti: { zh: "海地", en: "Haiti" },
  "Dominican Republic": { zh: "多米尼加共和国", en: "Dominican Republic" },
  "Puerto Rico": { zh: "波多黎各", en: "Puerto Rico" },
  "Trinidad and Tobago": { zh: "特立尼达和多巴哥", en: "Trinidad and Tobago" },
  Barbados: { zh: "巴巴多斯", en: "Barbados" },
  "Saint Lucia": { zh: "圣卢西亚", en: "Saint Lucia" },
  "Saint Vincent and the Grenadines": {
    zh: "圣文森特和格林纳丁斯",
    en: "Saint Vincent and the Grenadines",
  },
  Grenada: { zh: "格林纳达", en: "Grenada" },
  "Antigua and Barbuda": { zh: "安提瓜和巴布达", en: "Antigua and Barbuda" },
  Dominica: { zh: "多米尼克", en: "Dominica" },
  "Saint Kitts and Nevis": {
    zh: "圣基茨和尼维斯",
    en: "Saint Kitts and Nevis",
  },
  Bahamas: { zh: "巴哈马", en: "Bahamas" },
  "Turks and Caicos Islands": {
    zh: "特克斯和凯科斯群岛",
    en: "Turks and Caicos Islands",
  },
  "Cayman Islands": { zh: "开曼群岛", en: "Cayman Islands" },
  Bermuda: { zh: "百慕大", en: "Bermuda" },
  "British Virgin Islands": {
    zh: "英属维尔京群岛",
    en: "British Virgin Islands",
  },
  "United States Virgin Islands": {
    zh: "美属维尔京群岛",
    en: "United States Virgin Islands",
  },
  Aruba: { zh: "阿鲁巴", en: "Aruba" },
  Curacao: { zh: "库拉索", en: "Curacao" },
  "Sint Maarten": { zh: "荷属圣马丁", en: "Sint Maarten" },
  "Saint Martin": { zh: "法属圣马丁", en: "Saint Martin" },
  "Saint Barthelemy": { zh: "圣巴泰勒米", en: "Saint Barthelemy" },
  "Bonaire, Saint Eustatius and Saba": {
    zh: "博内尔、圣尤斯特歇斯和萨巴",
    en: "Bonaire, Saint Eustatius and Saba",
  },
  Guadeloupe: { zh: "瓜德罗普", en: "Guadeloupe" },
  Martinique: { zh: "马提尼克", en: "Martinique" },
  Montserrat: { zh: "蒙特塞拉特", en: "Montserrat" },
  Anguilla: { zh: "安圭拉", en: "Anguilla" },
  // 南美
  Brazil: { zh: "巴西", en: "Brazil" },
  Argentina: { zh: "阿根廷", en: "Argentina" },
  Chile: { zh: "智利", en: "Chile" },
  Colombia: { zh: "哥伦比亚", en: "Colombia" },
  Peru: { zh: "秘鲁", en: "Peru" },
  Venezuela: { zh: "委内瑞拉", en: "Venezuela" },
  Ecuador: { zh: "厄瓜多尔", en: "Ecuador" },
  Bolivia: { zh: "玻利维亚", en: "Bolivia" },
  Paraguay: { zh: "巴拉圭", en: "Paraguay" },
  Uruguay: { zh: "乌拉圭", en: "Uruguay" },
  Guyana: { zh: "圭亚那", en: "Guyana" },
  Suriname: { zh: "苏里南", en: "Suriname" },
  "French Guiana": { zh: "法属圭亚那", en: "French Guiana" },
  "Falkland Is.": { zh: "福克兰群岛", en: "Falkland Islands" },
  "Falkland Islands": { zh: "福克兰群岛", en: "Falkland Islands" },
  // 西欧
  "United Kingdom": { zh: "英国", en: "United Kingdom" },
  Ireland: { zh: "爱尔兰", en: "Ireland" },
  France: { zh: "法国", en: "France" },
  Germany: { zh: "德国", en: "Germany" },
  Netherlands: { zh: "荷兰", en: "Netherlands" },
  Belgium: { zh: "比利时", en: "Belgium" },
  Luxembourg: { zh: "卢森堡", en: "Luxembourg" },
  Switzerland: { zh: "瑞士", en: "Switzerland" },
  Austria: { zh: "奥地利", en: "Austria" },
  Spain: { zh: "西班牙", en: "Spain" },
  Portugal: { zh: "葡萄牙", en: "Portugal" },
  Italy: { zh: "意大利", en: "Italy" },
  Monaco: { zh: "摩纳哥", en: "Monaco" },
  Andorra: { zh: "安道尔", en: "Andorra" },
  "San Marino": { zh: "圣马力诺", en: "San Marino" },
  Vatican: { zh: "梵蒂冈", en: "Vatican" },
  "Vatican City": { zh: "梵蒂冈", en: "Vatican City" },
  Liechtenstein: { zh: "列支敦士登", en: "Liechtenstein" },
  Gibraltar: { zh: "直布罗陀", en: "Gibraltar" },
  // 北欧
  Sweden: { zh: "瑞典", en: "Sweden" },
  Norway: { zh: "挪威", en: "Norway" },
  Finland: { zh: "芬兰", en: "Finland" },
  Denmark: { zh: "丹麦", en: "Denmark" },
  Iceland: { zh: "冰岛", en: "Iceland" },
  "Faroe Is.": { zh: "法罗群岛", en: "Faroe Islands" },
  "Faroe Islands": { zh: "法罗群岛", en: "Faroe Islands" },
  Aland: { zh: "奥兰群岛", en: "Åland Islands" },
  "Åland Islands": { zh: "奥兰群岛", en: "Åland Islands" },
  "Svalbard and Jan Mayen": {
    zh: "斯瓦尔巴和扬马延",
    en: "Svalbard and Jan Mayen",
  },
  // 南欧
  Greece: { zh: "希腊", en: "Greece" },
  Cyprus: { zh: "塞浦路斯", en: "Cyprus" },
  Malta: { zh: "马耳他", en: "Malta" },
  // 东欧
  Russia: { zh: "俄罗斯", en: "Russia" },
  Ukraine: { zh: "乌克兰", en: "Ukraine" },
  Belarus: { zh: "白俄罗斯", en: "Belarus" },
  Poland: { zh: "波兰", en: "Poland" },
  "Czech Republic": { zh: "捷克", en: "Czech Republic" },
  Czechia: { zh: "捷克", en: "Czechia" },
  Slovakia: { zh: "斯洛伐克", en: "Slovakia" },
  Hungary: { zh: "匈牙利", en: "Hungary" },
  Romania: { zh: "罗马尼亚", en: "Romania" },
  Bulgaria: { zh: "保加利亚", en: "Bulgaria" },
  Moldova: { zh: "摩尔多瓦", en: "Moldova" },
  Lithuania: { zh: "立陶宛", en: "Lithuania" },
  Latvia: { zh: "拉脱维亚", en: "Latvia" },
  Estonia: { zh: "爱沙尼亚", en: "Estonia" },
  // 巴尔干
  Serbia: { zh: "塞尔维亚", en: "Serbia" },
  Kosovo: { zh: "科索沃", en: "Kosovo" },
  Croatia: { zh: "克罗地亚", en: "Croatia" },
  Slovenia: { zh: "斯洛文尼亚", en: "Slovenia" },
  "Bosnia and Herzegovina": { zh: "波黑", en: "Bosnia and Herzegovina" },
  Montenegro: { zh: "黑山", en: "Montenegro" },
  Albania: { zh: "阿尔巴尼亚", en: "Albania" },
  Macedonia: { zh: "北马其顿", en: "North Macedonia" },
  "North Macedonia": { zh: "北马其顿", en: "North Macedonia" },
  // 北非
  Egypt: { zh: "埃及", en: "Egypt" },
  Libya: { zh: "利比亚", en: "Libya" },
  Tunisia: { zh: "突尼斯", en: "Tunisia" },
  Algeria: { zh: "阿尔及利亚", en: "Algeria" },
  Morocco: { zh: "摩洛哥", en: "Morocco" },
  "W. Sahara": { zh: "西撒哈拉", en: "Western Sahara" },
  "Western Sahara": { zh: "西撒哈拉", en: "Western Sahara" },
  Sudan: { zh: "苏丹", en: "Sudan" },
  // 东非
  Ethiopia: { zh: "埃塞俄比亚", en: "Ethiopia" },
  Eritrea: { zh: "厄立特里亚", en: "Eritrea" },
  Djibouti: { zh: "吉布提", en: "Djibouti" },
  Somalia: { zh: "索马里", en: "Somalia" },
  Kenya: { zh: "肯尼亚", en: "Kenya" },
  Tanzania: { zh: "坦桑尼亚", en: "Tanzania" },
  "United Republic of Tanzania": { zh: "坦桑尼亚", en: "Tanzania" },
  Uganda: { zh: "乌干达", en: "Uganda" },
  Rwanda: { zh: "卢旺达", en: "Rwanda" },
  Burundi: { zh: "布隆迪", en: "Burundi" },
  "S. Sudan": { zh: "南苏丹", en: "South Sudan" },
  "South Sudan": { zh: "南苏丹", en: "South Sudan" },
  // 西非
  Nigeria: { zh: "尼日利亚", en: "Nigeria" },
  Ghana: { zh: "加纳", en: "Ghana" },
  Senegal: { zh: "塞内加尔", en: "Senegal" },
  "Ivory Coast": { zh: "科特迪瓦", en: "Ivory Coast" },
  "Côte d'Ivoire": { zh: "科特迪瓦", en: "Ivory Coast" },
  Cameroon: { zh: "喀麦隆", en: "Cameroon" },
  Mali: { zh: "马里", en: "Mali" },
  "Burkina Faso": { zh: "布基纳法索", en: "Burkina Faso" },
  Niger: { zh: "尼日尔", en: "Niger" },
  Chad: { zh: "乍得", en: "Chad" },
  Mauritania: { zh: "毛里塔尼亚", en: "Mauritania" },
  Gambia: { zh: "冈比亚", en: "Gambia" },
  "Guinea-Bissau": { zh: "几内亚比绍", en: "Guinea-Bissau" },
  Guinea: { zh: "几内亚", en: "Guinea" },
  "Sierra Leone": { zh: "塞拉利昂", en: "Sierra Leone" },
  Liberia: { zh: "利比里亚", en: "Liberia" },
  Togo: { zh: "多哥", en: "Togo" },
  Benin: { zh: "贝宁", en: "Benin" },
  "Cape Verde": { zh: "佛得角", en: "Cape Verde" },
  "Sao Tome and Principe": {
    zh: "圣多美和普林西比",
    en: "Sao Tome and Principe",
  },
  // 中非
  "Central African Rep.": { zh: "中非共和国", en: "Central African Republic" },
  "Central African Republic": {
    zh: "中非共和国",
    en: "Central African Republic",
  },
  Congo: { zh: "刚果共和国", en: "Republic of the Congo" },
  "Dem. Rep. Congo": { zh: "刚果民主共和国", en: "DR Congo" },
  "Democratic Republic of the Congo": { zh: "刚果民主共和国", en: "DR Congo" },
  Gabon: { zh: "加蓬", en: "Gabon" },
  "Eq. Guinea": { zh: "赤道几内亚", en: "Equatorial Guinea" },
  "Equatorial Guinea": { zh: "赤道几内亚", en: "Equatorial Guinea" },
  Angola: { zh: "安哥拉", en: "Angola" },
  // 南非洲
  "South Africa": { zh: "南非", en: "South Africa" },
  Namibia: { zh: "纳米比亚", en: "Namibia" },
  Botswana: { zh: "博茨瓦纳", en: "Botswana" },
  Zimbabwe: { zh: "津巴布韦", en: "Zimbabwe" },
  Zambia: { zh: "赞比亚", en: "Zambia" },
  Malawi: { zh: "马拉维", en: "Malawi" },
  Mozambique: { zh: "莫桑比克", en: "Mozambique" },
  Swaziland: { zh: "斯威士兰", en: "Eswatini" },
  eSwatini: { zh: "斯威士兰", en: "Eswatini" },
  Lesotho: { zh: "莱索托", en: "Lesotho" },
  // 印度洋岛屿 & 东非岛屿
  Madagascar: { zh: "马达加斯加", en: "Madagascar" },
  Mauritius: { zh: "毛里求斯", en: "Mauritius" },
  Seychelles: { zh: "塞舌尔", en: "Seychelles" },
  Comoros: { zh: "科摩罗", en: "Comoros" },
  Reunion: { zh: "留尼汪", en: "Réunion" },
  Mayotte: { zh: "马约特", en: "Mayotte" },
  "Saint Helena": { zh: "圣赫勒拿", en: "Saint Helena" },
  "Br. Indian Ocean Ter.": {
    zh: "英属印度洋领地",
    en: "British Indian Ocean Territory",
  },
  // 大洋洲
  Australia: { zh: "澳大利亚", en: "Australia" },
  "New Zealand": { zh: "新西兰", en: "New Zealand" },
  "Papua New Guinea": { zh: "巴布亚新几内亚", en: "Papua New Guinea" },
  Fiji: { zh: "斐济", en: "Fiji" },
  "Solomon Is.": { zh: "所罗门群岛", en: "Solomon Islands" },
  "Solomon Islands": { zh: "所罗门群岛", en: "Solomon Islands" },
  Vanuatu: { zh: "瓦努阿图", en: "Vanuatu" },
  "New Caledonia": { zh: "新喀里多尼亚", en: "New Caledonia" },
  Samoa: { zh: "萨摩亚", en: "Samoa" },
  Tonga: { zh: "汤加", en: "Tonga" },
  Kiribati: { zh: "基里巴斯", en: "Kiribati" },
  Micronesia: { zh: "密克罗尼西亚", en: "Micronesia" },
  "Marshall Is.": { zh: "马绍尔群岛", en: "Marshall Islands" },
  "Marshall Islands": { zh: "马绍尔群岛", en: "Marshall Islands" },
  Palau: { zh: "帕劳", en: "Palau" },
  Nauru: { zh: "瑙鲁", en: "Nauru" },
  Tuvalu: { zh: "图瓦卢", en: "Tuvalu" },
  "Cook Islands": { zh: "库克群岛", en: "Cook Islands" },
  Niue: { zh: "纽埃", en: "Niue" },
  "Wallis and Futuna": { zh: "瓦利斯和富图纳", en: "Wallis and Futuna" },
  "Fr. Polynesia": { zh: "法属波利尼西亚", en: "French Polynesia" },
  "French Polynesia": { zh: "法属波利尼西亚", en: "French Polynesia" },
  Guam: { zh: "关岛", en: "Guam" },
  "N. Mariana Is.": { zh: "北马里亚纳群岛", en: "Northern Mariana Islands" },
  "American Samoa": { zh: "美属萨摩亚", en: "American Samoa" },
  "Norfolk Island": { zh: "诺福克岛", en: "Norfolk Island" },
  "Cocos (Keeling) Islands": { zh: "科科斯群岛", en: "Cocos Islands" },
  "Christmas Island": { zh: "圣诞岛", en: "Christmas Island" },
  Tokelau: { zh: "托克劳", en: "Tokelau" },
  "Pitcairn Is.": { zh: "皮特凯恩群岛", en: "Pitcairn Islands" },
  // 大西洋 & 偏远领地
  "S. Georgia and S. Sandwich Isl.": {
    zh: "南乔治亚和南桑威奇群岛",
    en: "South Georgia",
  },
  "Bouvet Island": { zh: "布韦岛", en: "Bouvet Island" },
  "Heard I. and McDonald Is.": {
    zh: "赫德岛和麦克唐纳群岛",
    en: "Heard Island",
  },
  "Fr. S. Antarctic Lands": {
    zh: "法属南部领地",
    en: "French Southern Territories",
  },
  "United States Minor Outlying Islands": {
    zh: "美国本土外小岛屿",
    en: "US Minor Outlying Islands",
  },
  // 极地
  Antarctica: { zh: "南极洲", en: "Antarctica" },
};

export function getDisplayCountryName(
  countryName: string,
  locale: string | undefined,
) {
  const normalizedLocale = locale?.toLowerCase() ?? "zh-cn";
  const preferredLanguage = normalizedLocale.startsWith("zh") ? "zh" : "en";
  const fallback = COUNTRY_NAME_FALLBACK[countryName];
  if (fallback) return fallback[preferredLanguage];
  return countryName;
}
